### PR TITLE
Start with empty input.

### PR DESCRIPTION
**Pull request by wannymiarelli**
If the input is empty the select object is null and return a TypeError. So just added a check to ensure that select is not null.

### CODE REVIEW

**Comment by Toilal** [comment]
Thanks ! Could you add this to `pickATime` directive too ?

**Comment by wannymiarelli** [comment]
Done with pleasure.

**Comment by Toilal** [comment]
Thanks, i've merged manually to keep a single commit.

**Comment by Toilal** [comment]
And released as `0.1.5`.

**Pull request closed without merging**
